In [1]:
import pandas as pd

In [2]:
from google.colab import drive
import os

drive.mount('/content/drive')
datasets_path = '/content/drive/MyDrive/Dataset'
files = os.listdir(datasets_path)

for f in files:
    print(f)

Mounted at /content/drive
kc_house_data.csv
bands.csv
movie_titles.tsv
chess.csv
countries of the world.csv
crime.csv
offense_codes.csv
Salaries.csv
pollution.csv
bestsellers.csv
JoeBidenTweets.csv
world-happiness-report-2021.csv
laliga.csv
STEM_Salaries.csv
nst-est2020.csv
titanic.csv
states.csv
nuforc_reports.csv
coin_Bitcoin.csv
netflix_titles.csv
billboard_charts.csv
sales.csv
game_stats.csv
mount_everest_deaths.csv
Pokemon.csv
car_stocks.csv
denver_crime.csv
state_pops.csv
insurance.csv
Data.csv

In [3]:
def load_dataset(filename, base_dir='/content/drive/MyDrive/Dataset', **kwargs):
    from pathlib import Path
    import pandas as pd
    return pd.read_csv(Path(base_dir) / filename, **kwargs)

In [4]:
states = load_dataset("states.csv")
states.head()

        State  Abbrev Code
0     Alabama    Ala.   AL
1      Alaska  Alaska   AK
2     Arizona   Ariz.   AZ
3    Arkansas    Ark.   AR
4  California  Calif.   CA


# **King County Home Sales Data Set**


This dataset includes the home sales from 2014-2015 in King County, WA (the county Seattle is located in)

## Description

This dataset includes the home sales from 2014–2015 in King County, WA (the county Seattle is located in):

1. **id** – House's unique ID  
2. **date** – Sale date  
3. **price** – Sale price  
4. **bedrooms** – Number of bedrooms  
5. **bathrooms** – Number of bathrooms  
6. **sqft_living** – Living space square footage  
7. **sqft_lot** – Total lot square footage  
8. **floors** – Number of floors  
9. **waterfront** – Is the house waterfront (1) or not (0)  
10. **view** – Rating from 0 to 4 of how good the view from the house is  
11. **condition** – Rating from 1 (poor) to 5 (very good) of the house's condition  
12. **grade** – Rating from 1 to 13 representing construction quality  
13. **sqft_above** – Square footage of the interior above ground level  
14. **sqft_basement** – Square footage of the interior below ground level  
15. **yr_built** – Year the house was initially built  
16. **yr_renovated** – Year of the house’s last renovation (if any)  
17. **zipcode** – Zipcode where the house is located  
18. **lat** – Property’s latitude  
19. **long** – Property’s longitude  
20. **sqft_living15** – Average interior space square footage of the nearest 15 neighbors  
21. **sqft_lot15** – Average lot square footage of the nearest 15 neighbors

In [5]:
houses = load_dataset("kc_house_data.csv")
houses.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [6]:
type(houses)

pandas.core.frame.DataFrame

In [7]:
len(houses)

21613

In [8]:
houses.shape

(21613, 21)

In [9]:
states.shape

(51, 3)

In [10]:
houses.size

453873

In [11]:
houses.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [12]:
first_5 = houses.head()

In [13]:
first_5

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [14]:
type(first_5)

pandas.core.frame.DataFrame

In [15]:
houses.head(200)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,7796450200,20140515T000000,256883.0,3,2.50,1690,5025,2.0,0,0,...,8,1690,0,2003,0,98023,47.2779,-122.347,2550,5001
196,7549802535,20141111T000000,423000.0,4,2.00,1970,6480,1.5,0,0,...,7,1130,840,1920,0,98108,47.5511,-122.312,1500,6480
197,3278600320,20140723T000000,465000.0,3,2.50,2150,4084,2.0,0,0,...,8,2150,0,2007,0,98126,47.5488,-122.372,1750,2385
198,2824079053,20150113T000000,440000.0,3,2.50,1910,66211,2.0,0,0,...,7,1910,0,1997,0,98024,47.5385,-121.911,2330,67268
199,1222069094,20141014T000000,385000.0,3,1.75,1350,155073,1.0,0,0,...,7,1350,0,1969,0,98038,47.4058,-121.994,1560,50965

In [16]:
last_5_states = states.tail()

In [17]:
last_5_states

            State Abbrev Code
46       Virginia    Va.   VA
47     Washington  Wash.   WA
48  West Virginia  W.Va.   WV
49      Wisconsin   Wis.   WI
50        Wyoming   Wyo.   WY

In [18]:
states.tail(15)

             State Abbrev Code
36        Oklahoma  Okla.   OK
37          Oregon   Ore.   OR
38    Pennsylvania    Pa.   PA
39    Rhode Island   R.I.   RI
40  South Carolina   S.C.   SC
41    South Dakota   S.D.   SD
42       Tennessee  Tenn.   TN
43           Texas   Tex.   TX
44            Utah   Utah   UT
45         Vermont    Vt.   VT
46        Virginia    Va.   VA
47      Washington  Wash.   WA
48   West Virginia  W.Va.   WV
49       Wisconsin   Wis.   WI
50         Wyoming   Wyo.   WY

In [19]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [20]:
states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   51 non-null     object
 1   Abbrev  51 non-null     object
 2   Code    51 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [21]:
houses.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [22]:
states.dtypes

State     object
Abbrev    object
Code      object
dtype: object

In [23]:
titanic = load_dataset("titanic.csv")
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [24]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

* `pclass` - Passenger Class (1 = 1st; 2 = 2nd; 3 = 3rd)
* `survived` - Survival (0 = No; 1 = Yes)
* `name` - Name
* `sex` - Sex
* `age` - Age
* `sibsp` - Number of Siblings/Spouses Aboard
* `parch` - Number of Parents/Children Aboard
* `ticket` - Ticket Number
* `fare` - Passenger Fare
* `cabin` - Cabin
* `embarked` - Port of Embarkation (C = Cherbourg; Q = Queenstown; S = Southampton)
* `boat` - Lifeboat (if survived)
* `body` - Body number (if did not survive and body was recovered)
* `home.dest` - Home/Destination

In [25]:
titanic.tail(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1299,3,0,"Yasbeck, Mr. Antoni",male,27,1,0,2659,14.4542,?,C,C,?,?
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15,1,0,2659,14.4542,?,C,?,?,?
1301,3,0,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,?,C,?,312,?
1302,3,0,"Yousif, Mr. Wazli",male,?,0,0,2647,7.225,?,C,?,?,?
1303,3,0,"Yousseff, Mr. Gerious",male,?,0,0,2627,14.4583,?,C,?,?,?
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

In [26]:
titanic.info

<bound method DataFrame.info of       pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton
1          1         1                   Allison, Master. Hudson Trevor
2          1         0                     Allison, Miss. Helen Loraine
3          1         0             Allison, Mr. Hudson Joshua Creighton
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...      ...       ...                                              ...
1304       3         0                             Zabour, Miss. Hileni
1305       3         0                            Zabour, Miss. Thamine
1306       3         0                        Zakarian, Mr. Mapriededer
1307       3         0                              Zakarian, Mr. Ortin
1308       3         0                               Zimmerman, Mr. Leo

         sex     age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female      29      0      0   24160  211.3375       B5        S    2
1       male  0.9167      1      2  113781    151.55  C22 C26        S   11
2     female       2      1      2  113781    151.55  C22 C26        S    ?
3       male      30      1      2  113781    151.55  C22 C26        S    ?
4     female      25      1      2  113781    151.55  C22 C26        S    ?
...      ...     ...    ...    ...     ...       ...      ...      ...  ...
1304  female    14.5      1      0    2665   14.4542        ?        C    ?
1305  female       ?      1      0    2665   14.4542        ?        C    ?
1306    male    26.5      0      0    2656     7.225        ?        C    ?
1307    male      27      0      0    2670     7.225        ?        C    ?
1308    male      29      0      0  315082     7.875        ?        S    ?

     body                        home.dest
0       ?                     St Louis, MO
1       ?  Montreal, PQ / Chesterville, ON
2       ?  Montreal, PQ / Chesterville, ON
3     135  Montreal, PQ / Chesterville, ON
4       ?  Montreal, PQ / Chesterville, ON
...   ...                              ...
1304  328                                ?
1305    ?                                ?
1306  304                                ?
1307    ?                                ?
1308    ?                                ?

[1309 rows x 14 columns]>

In [27]:
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

## read_csv with non-comma separators
The `netflix_titles.csv` file is actually pipe (`|`) separated.  We can tell `read_csv` to expect this using the `sep="|"` option.

Additionally, the netflix dataset includes an index column as the very first column.  We can let `read_csv` know using `index_col=0`

In [28]:

netflix = load_dataset("netflix_titles.csv", sep="|",index_col=0)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [29]:
netflix = load_dataset("netflix_titles.csv", sep="|",index_col=3)
netflix

,Unnamed: 0,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
title,,,,,,,,,,,,
Dick Johnson Is Dead,0,s1,Movie,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
Blood & Water,1,s2,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
Ganglands,2,s3,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
Jailbirds New Orleans,3,s4,TV Show,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
Kota Factory,4,s5,TV Show,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
Zodiac,8802,s8803,Movie,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
Zombie Dumb,8803,s8804,TV Show,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
Zombieland,8804,s8805,Movie,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
Zoom,8805,s8806,Movie,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
Zubaan,8806,s8807,Movie,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [30]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8807 entries, Dick Johnson Is Dead to Zubaan
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8807 non-null   int64
 1   show_id       8807 non-null   object
 2   type          8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(2), object(10)
memory usage: 894.5+ KB

In [31]:
netflix.head()

,Unnamed: 0,show_id,type,director,cast,country,date_added,release_year,rating,duration,listed_in,description
title,,,,,,,,,,,,
Dick Johnson Is Dead,0,s1,Movie,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
Blood & Water,1,s2,TV Show,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
Ganglands,2,s3,TV Show,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
Jailbirds New Orleans,3,s4,TV Show,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
Kota Factory,4,s5,TV Show,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [32]:
state_population = load_dataset("nst-est2020.csv")
state_population.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE042020,POPESTIMATE2020
0,10,0,0,0,United States,308745538,308758105,309327143,311583481,313877662,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329398742,329484123
1,20,1,0,0,Northeast Region,55317240,55318414,55380764,55608318,55782661,55912775,56021339,56052790,56063777,56083383,56084543,56002934,55924275,55849869
2,20,2,0,0,Midwest Region,66927001,66929737,66975328,67164092,67348275,67576524,67765576,67885682,68018175,68160342,68263019,68340091,68357895,68316744
3,20,3,0,0,South Region,114555744,114563042,114869421,116019483,117264196,118397213,119666248,121049223,122419547,123611036,124649156,125686544,126494232,126662754
4,20,4,0,0,West Region,71945553,71946912,72101630,72791588,73482530,74173435,74933166,75751299,76570256,77267367,77841481,78300384,78622340,78654756

In [33]:
state_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SUMLEV             57 non-null     int64
 1   REGION             57 non-null     object
 2   DIVISION           57 non-null     object
 3   STATE              57 non-null     int64
 4   NAME               57 non-null     object
 5   CENSUS2010POP      57 non-null     int64
 6   ESTIMATESBASE2010  57 non-null     int64
 7   POPESTIMATE2010    57 non-null     int64
 8   POPESTIMATE2011    57 non-null     int64
 9   POPESTIMATE2012    57 non-null     int64
 10  POPESTIMATE2013    57 non-null     int64
 11  POPESTIMATE2014    57 non-null     int64
 12  POPESTIMATE2015    57 non-null     int64
 13  POPESTIMATE2016    57 non-null     int64
 14  POPESTIMATE2017    57 non-null     int64
 15  POPESTIMATE2018    57 non-null     int64
 16  POPESTIMATE2019    57 non-null     int64
 17  POPESTIMATE042020  57 non-null     int64
 18  POPESTIMATE2020    57 non-null     int64
dtypes: int64(16), object(3)
memory usage: 8.6+ KB

In [34]:
names = ['sumlev', 'region', 'division', 'state', 'name', 'census2010pop', 'estimatesbase2010', 'popestimate2010', 'popestimate2011', 'popestimate2012', 'popestimate2013', 'popestimate2014', 'popestimate2015', 'popestimate2016', 'popestimate2017', 'popestimate2018', 'popestimate2019', 'popestimate042020', 'popestimate2020']

In [35]:
state_population = load_dataset("nst-est2020.csv",names=names)
state_population.head()

,sumlev,region,division,state,name,census2010pop,estimatesbase2010,popestimate2010,popestimate2011,popestimate2012,popestimate2013,popestimate2014,popestimate2015,popestimate2016,popestimate2017,popestimate2018,popestimate2019,popestimate042020,popestimate2020
0,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE042020,POPESTIMATE2020
1,010,0,0,00,United States,308745538,308758105,309327143,311583481,313877662,316059947,318386329,320738994,323071755,325122128,326838199,328329953,329398742,329484123
2,020,1,0,00,Northeast Region,55317240,55318414,55380764,55608318,55782661,55912775,56021339,56052790,56063777,56083383,56084543,56002934,55924275,55849869
3,020,2,0,00,Midwest Region,66927001,66929737,66975328,67164092,67348275,67576524,67765576,67885682,68018175,68160342,68263019,68340091,68357895,68316744
4,020,3,0,00,South Region,114555744,114563042,114869421,116019483,117264196,118397213,119666248,121049223,122419547,123611036,124649156,125686544,126494232,126662754